# Generated by Django 4.2.4 on 2023-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
